### ISSUE TITLE
Linking Uses cases to astronomical projects 

### ISSUE THREAD

**Issue by loumir** [ivoa/dm-usecases#3]
The current uses cases tree is built-up following the organisation of metadata used in data files ( columns in VOTables).
It aims at covering multiple scenarios of arrangements of identifiers, measures, reference systems , calibration metadata, etc. and their relations to each other.
Many astronomical projects encounter these kinds of metadata arrangements
I would be interested  to see a cross table, between a use case  listed in this tree and the various projects, Chandra, Mast , Gavo, Gaia, Vizier, etc... with the various levels of interest, and implication  :  
- (C) concerned with this use-case  
- (T)  testing various solutions
- (I) implementing this use case in routine already 

| Usecase vs Project | Gaia | Chandra | GLAST | LSST | Gavo | Vizier | "my project" |
| :---| :---: | :---: | :---: | :---: | :---: | :---: | :---: |
_combined_data_       | C, T? | C? | C? | C? | T, I | T, I |                
_column_grouping_    | C, T? | | | | T, I | T, I |  

and each project could feed this table during progress. 
 
The idea is to have an overview of the use case coverage, and of the DM experience feedback at various places.  
Thanks .

**Comment by lmichel** [comment]
Done
